// grammar-parser.js - Processes XML generated by REx
const xml2js = require('xml2js');

class GrammarParser {
  constructor(xmlString) {
    this.xmlString = xmlString;
    this.rules = new Map();
    this.tokens = new Map();
    this.startSymbol = null;
  }
  
  async parse() {
    const parser = new xml2js.Parser({ explicitArray: false, mergeAttrs: true });
    const result = await parser.parseStringPromise(this.xmlString);
    
    // Extract syntax rules
    const syntaxDefinition = result.Grammar.SyntaxDefinition;
    if (syntaxDefinition && syntaxDefinition.SyntaxProduction) {
      const productions = Array.isArray(syntaxDefinition.SyntaxProduction) 
        ? syntaxDefinition.SyntaxProduction 
        : [syntaxDefinition.SyntaxProduction];
      
      for (const prod of productions) {
        const rule = this.parseSyntaxProduction(prod);
        this.rules.set(rule.name, rule);
        
        // Set start symbol to the first rule
        if (!this.startSymbol) {
          this.startSymbol = rule.name;
        }
      }
    }
    
    // Extract lexical rules
    const lexicalDefinition = result.Grammar.LexicalDefinition;
    if (lexicalDefinition && lexicalDefinition.LexicalProduction) {
      const productions = Array.isArray(lexicalDefinition.LexicalProduction)
        ? lexicalDefinition.LexicalProduction
        : [lexicalDefinition.LexicalProduction];
      
      for (const prod of productions) {
        const token = this.parseLexicalProduction(prod);
        this.tokens.set(token.name, token);
      }
    }
    
    return {
      rules: this.rules,
      tokens: this.tokens,
      startSymbol: this.startSymbol
    };
  }
  
  parseSyntaxProduction(prod) {
    const name = prod.Name;
    const syntaxChoice = prod.SyntaxChoice;
    const sequences = this.parseSyntaxChoice(syntaxChoice);
    const options = this.parseOptions(prod.Option);
    
    return {
      type: 'syntax',
      name: name,
      sequences: sequences,
      options: options
    };
  }
  
  parseSyntaxChoice(choice) {
    const sequences = [];
    
    // If there is no SyntaxSequence, return empty
    if (!choice || !choice.SyntaxSequence) {
      return sequences;
    }
    
    const seqElements = Array.isArray(choice.SyntaxSequence) 
      ? choice.SyntaxSequence 
      : [choice.SyntaxSequence];
    
    for (const seq of seqElements) {
      const items = this.parseSyntaxSequence(seq);
      sequences.push(items);
    }
    
    return sequences;
  }
  
  parseSyntaxSequence(seq) {
    const items = [];
    
    if (!seq.SyntaxItem) {
      return items;
    }
    
    const itemElements = Array.isArray(seq.SyntaxItem) 
      ? seq.SyntaxItem 
      : [seq.SyntaxItem];
    
    for (const item of itemElements) {
      const parsedItem = this.parseSyntaxItem(item);
      if (parsedItem) {
        items.push(parsedItem);
      }
    }
    
    return items;
  }
  
  parseSyntaxItem(item) {
    const primary = item.SyntaxPrimary;
    if (!primary) return null;
    
    // Extract quantifier
    let quantifier = 'exactly1';
    const tokenElements = item.TOKEN;
    if (tokenElements) {
      const tokens = Array.isArray(tokenElements) ? tokenElements : [tokenElements];
      for (const token of tokens) {
        if (token === '?' && quantifier === 'exactly1') quantifier = 'optional';
        if (token === '*') quantifier = 'zeroOrMore';
        if (token === '+') quantifier = 'oneOrMore';
      }
    }
    
    const primaryContent = this.parseSyntaxPrimary(primary);
    
    return {
      ...primaryContent,
      quantifier: quantifier
    };
  }
  
  parseSyntaxPrimary(primary) {
    // NameOrString
    if (primary.NameOrString) {
      const nos = primary.NameOrString;
      if (nos.Name) {
        return { type: 'nonterminal', value: nos.Name };
      }
      if (nos.StringLiteral) {
        return { type: 'terminal', value: this.unescapeString(nos.StringLiteral) };
      }
    }
    
    // Direct StringLiteral
    if (primary.StringLiteral) {
      return { type: 'terminal', value: this.unescapeString(primary.StringLiteral) };
    }
    
    // Direct Name
    if (primary.Name) {
      return { type: 'nonterminal', value: primary.Name };
    }
    
    // Parenthesized group
    if (primary.SyntaxChoice) {
      return {
        type: 'group',
        sequences: this.parseSyntaxChoice(primary.SyntaxChoice)
      };
    }
    
    return null;
  }
  
  parseLexicalProduction(prod) {
    const name = prod.Name;
    const contextChoice = prod.ContextChoice;
    const patterns = this.parseContextChoice(contextChoice);
    const options = this.parseOptions(prod.Option);
    
    // Check whether this is a skip token (whitespace)
    const isSkip = options && options.some(opt => opt === 'definition');
    
    return {
      type: 'lexical',
      name: name,
      patterns: patterns,
      isSkip: isSkip
    };
  }
  
  parseContextChoice(choice) {
    const patterns = [];
    
    if (!choice || !choice.ContextExpression) {
      return patterns;
    }
    
    const expressions = Array.isArray(choice.ContextExpression)
      ? choice.ContextExpression
      : [choice.ContextExpression];
    
    for (const expr of expressions) {
      const pattern = this.parseContextExpression(expr);
      patterns.push(pattern);
    }
    
    return patterns;
  }
  
  parseContextExpression(expr) {
    const lexicalSequence = expr.LexicalSequence;
    const patterns = this.parseLexicalSequence(lexicalSequence);
    return patterns;
  }
  
  parseLexicalSequence(seq) {
    const items = [];
    
    if (!seq || !seq.LexicalItem) {
      return items;
    }
    
    const itemElements = Array.isArray(seq.LexicalItem)
      ? seq.LexicalItem
      : [seq.LexicalItem];
    
    for (const item of itemElements) {
      const parsedItem = this.parseLexicalItem(item);
      if (parsedItem) {
        items.push(parsedItem);
      }
    }
    
    return items;
  }
  
  parseLexicalItem(item) {
    const primary = item.LexicalPrimary;
    if (!primary) return null;
    
    let quantifier = 'exactly1';
    const tokenElements = item.TOKEN;
    if (tokenElements) {
      const tokens = Array.isArray(tokenElements) ? tokenElements : [tokenElements];
      for (const token of tokens) {
        if (token === '?' && quantifier === 'exactly1') quantifier = 'optional';
        if (token === '*') quantifier = 'zeroOrMore';
        if (token === '+') quantifier = 'oneOrMore';
      }
    }
    
    const primaryContent = this.parseLexicalPrimary(primary);
    
    return {
      ...primaryContent,
      quantifier: quantifier
    };
  }
  
  parseLexicalPrimary(primary) {
    // Name (reference to another token)
    if (primary.Name) {
      return { type: 'tokenRef', value: primary.Name };
    }
    
    // StringLiteral
    if (primary.StringLiteral) {
      return { type: 'literal', value: this.unescapeString(primary.StringLiteral) };
    }
    
    // CharClass
    if (primary.CharClass) {
      const parsed = this.parseCharClass(primary.CharClass);
      return { type: 'charclass', value: parsed.content, negated: parsed.negated };
    }
    
    // CharCode
    if (primary.CharCode) {
      return { type: 'literal', value: this.parseCharCode(primary.CharCode) };
    }
    
    // Char
    if (primary.Char) {
      return { type: 'literal', value: primary.Char };
    }
    
    // Parenthesized group
    if (primary.LexicalChoice) {
      return {
        type: 'group',
        patterns: this.parseLexicalChoice(primary.LexicalChoice)
      };
    }

    // Direct TOKEN in LexicalPrimary (e.g., '.' or '$')
    if (primary.TOKEN) {
      const token = Array.isArray(primary.TOKEN) ? primary.TOKEN[0] : primary.TOKEN;
      if (token === '.') {
        return { type: 'anyChar' };
      }
      if (token === '$') {
        // EOF is handled separately by the lexer (automatic EOF token)
        return { type: 'tokenRef', value: 'EOF' };
      }
      return { type: 'literal', value: token };
    }
    
    return null;
  }
  
  parseLexicalChoice(choice) {
    const patterns = [];
    
    if (!choice || !choice.LexicalSequence) {
      return patterns;
    }
    
    const sequences = Array.isArray(choice.LexicalSequence)
      ? choice.LexicalSequence
      : [choice.LexicalSequence];
    
    for (const seq of sequences) {
      const pattern = this.parseLexicalSequence(seq);
      patterns.push(pattern);
    }
    
    return patterns;
  }
  
  parseCharClass(charClass) {
    const toArray = (v) => (v == null ? [] : (Array.isArray(v) ? v : [v]));
    const tokenElements = toArray(charClass.TOKEN);
    const negated = tokenElements.includes('[^');

    // Extract char class content
    let content = '';

    for (const range of toArray(charClass.CharRange)) {
      content += range;
    }

    for (const ch of toArray(charClass.Char)) {
      content += ch;
    }

    for (const code of toArray(charClass.CharCode)) {
      content += this.parseCharCode(code);
    }

    for (const codeRange of toArray(charClass.CharCodeRange)) {
      content += this.parseCharCodeRange(codeRange);
    }

    return { content, negated };
  }

  parseCharCodeRange(rangeStr) {
    const m = String(rangeStr).match(/^#x([0-9a-fA-F]+)-#x([0-9a-fA-F]+)$/);
    if (!m) return '';

    const start = parseInt(m[1], 16);
    const end = parseInt(m[2], 16);

    // Without /u flag in the current generator, keep it in BMP for safety
    if (start > 0xFFFF || end > 0xFFFF) {
      return '';
    }

    return `${String.fromCodePoint(start)}-${String.fromCodePoint(end)}`;
  }
  
  parseCharCode(code) {
    // Convert #xNN into a Unicode character
    const codeStr = String(code);
    const match = codeStr.match(/#x([0-9a-fA-F]+)/);
    if (match) {
      return String.fromCodePoint(parseInt(match[1], 16));
    }
    return codeStr;
  }
  
  parseOptions(options) {
    if (!options) return [];
    
    const opts = Array.isArray(options) ? options : [options];
    const result = [];
    
    for (const opt of opts) {
      if (typeof opt === 'string') {
        if (opt === 'explicit') result.push('explicit');
        if (opt === 'definition') result.push('definition');
      } else if (opt && opt.TOKEN) {
        // xml2js returns Option as an object with TOKEN array, e.g. /* ws: definition */
        const tokens = Array.isArray(opt.TOKEN) ? opt.TOKEN : [opt.TOKEN];
        if (tokens.includes('definition')) result.push('definition');
        if (tokens.includes('explicit')) result.push('explicit');
      }
    }
    
    return result;
  }
  
  unescapeString(str) {
    // Remove surrounding quotes
    if (str.startsWith("'") && str.endsWith("'")) {
      return str.slice(1, -1);
    }
    if (str.startsWith('"') && str.endsWith('"')) {
      return str.slice(1, -1);
    }
    return str;
  }
}

module.exports = GrammarParser;