#!/usr/bin/env node
// index.js - Gerador de parser principal

const fs = require('fs');
const path = require('path');
const GrammarParser = require('./grammar-parser');
const CodeGenerator = require('./code-generator');

async function main() {
  const args = process.argv.slice(2);
  
  if (args.length < 1) {
    console.log(`
Usage: node index.js <grammar-xml-file> [output-file]

Options:
  grammar-xml-file   XML file generated by REx from EBNF grammar
  output-file        Optional output JavaScript file (default: parser.js)

Example:
  node index.js grammar.xml my-parser.js
`);
    process.exit(1);
  }
  
  const inputFile = args[0];
  const outputFile = args[1] || 'parser.js';
  
  console.log(`📖 Reading grammar XML from: ${inputFile}`);
  
  try {
    const xmlContent = fs.readFileSync(inputFile, 'utf8');
    
    console.log('🔍 Parsing grammar structure...');
    const grammarParser = new GrammarParser(xmlContent);
    const grammar = await grammarParser.parse();
    
    console.log(`📊 Found ${grammar.rules.size} syntax rules and ${grammar.tokens.size} lexical rules`);
    console.log(`🎯 Start symbol: ${grammar.startSymbol}`);
    
    console.log('⚙️  Generating JavaScript parser...');
    const generator = new CodeGenerator(grammar);
    const parserCode = generator.generate();
    
    fs.writeFileSync(outputFile, parserCode, 'utf8');
    console.log(`✅ Parser generated successfully: ${outputFile}`);
    
  } catch (error) {
    console.error('❌ Error:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

// Se executado diretamente
if (require.main === module) {
  main();
}

module.exports = { GrammarParser, CodeGenerator };