/* Gramática simples para expressões aritméticas */
Expression ::= Term ( '+' Term )*
Term       ::= Factor ( '*' Factor )*
Factor     ::= Number
             | '(' Expression ')'

<?TOKENS?>

Number     ::= [0-9]+

Whitespace ::= [#x0009#x000A#x000D#x0020]+
               /* ws: definition */
