'use strict';
// Tests for grammar-parser.js
// Run via: node --test tests/unit/grammar-parser.test.js

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs   = require('fs');
const path = require('path');

const GrammarParser = require('../../grammar-parser');

// ─── XML Fixtures ─────────────────────────────────────────────────────────────

// Committed grammar.xml (generated by REx from sample-grammar.ebnf)
const ARITHMETIC_XML = fs.readFileSync(
  path.join(__dirname, '../../grammar.xml'), 'utf8'
);

// Minimal grammar: Start ::= Word   /   Word ::= [a-z]+
const MINIMAL_XML =
  '<?xml version="1.0" encoding="UTF-8"?>' +
  '<Grammar><Prolog/>' +
  '<SyntaxDefinition>' +
    '<SyntaxProduction>' +
      '<Name>Start</Name> <TOKEN>::=</TOKEN>' +
      '<SyntaxChoice><SyntaxSequence>' +
        '<SyntaxItem><SyntaxPrimary><NameOrString>' +
          '<Name>Word</Name>' +
        '</NameOrString></SyntaxPrimary></SyntaxItem>' +
      '</SyntaxSequence></SyntaxChoice>' +
    '</SyntaxProduction>' +
  '</SyntaxDefinition>' +
  '<LexicalDefinition><TOKEN>&lt;?TOKENS?&gt;</TOKEN>' +
    '<LexicalProduction>' +
      '<Name>Word</Name> <TOKEN>::=</TOKEN>' +
      '<ContextChoice><ContextExpression><LexicalSequence>' +
        '<LexicalItem>' +
          '<LexicalPrimary><CharClass>' +
            '<TOKEN>[</TOKEN><CharRange>a-z</CharRange><TOKEN>]</TOKEN>' +
          '</CharClass></LexicalPrimary>' +
          '<TOKEN>+</TOKEN>' +
        '</LexicalItem>' +
      '</LexicalSequence></ContextExpression></ContextChoice>' +
    '</LexicalProduction>' +
  '</LexicalDefinition>' +
  '<EOF/></Grammar>';

// Regression fixture: multiple <CharCode> siblings + ws:definition option
// This was crashing with "code.match is not a function" before the fix.
const CHARCODE_XML =
  '<?xml version="1.0" encoding="UTF-8"?>' +
  '<Grammar><Prolog/>' +
  '<SyntaxDefinition>' +
    '<SyntaxProduction>' +
      '<Name>Start</Name> <TOKEN>::=</TOKEN>' +
      '<SyntaxChoice><SyntaxSequence>' +
        '<SyntaxItem><SyntaxPrimary><NameOrString>' +
          '<Name>Ws</Name>' +
        '</NameOrString></SyntaxPrimary></SyntaxItem>' +
      '</SyntaxSequence></SyntaxChoice>' +
    '</SyntaxProduction>' +
  '</SyntaxDefinition>' +
  '<LexicalDefinition><TOKEN>&lt;?TOKENS?&gt;</TOKEN>' +
    '<LexicalProduction>' +
      '<Name>Ws</Name> <TOKEN>::=</TOKEN>' +
      '<ContextChoice><ContextExpression><LexicalSequence>' +
        '<LexicalItem>' +
          '<LexicalPrimary><CharClass>' +
            '<TOKEN>[</TOKEN>' +
            '<CharCode>#x0009</CharCode>' +
            '<CharCode>#x000A</CharCode>' +
            '<CharCode>#x000D</CharCode>' +
            '<CharCode>#x0020</CharCode>' +
            '<TOKEN>]</TOKEN>' +
          '</CharClass></LexicalPrimary>' +
          '<TOKEN>+</TOKEN>' +
        '</LexicalItem>' +
      '</LexicalSequence></ContextExpression></ContextChoice>' +
      '<Option>' +
        '<TOKEN>/*</TOKEN><Space> </Space>' +
        '<TOKEN>ws</TOKEN><TOKEN>:</TOKEN><Space> </Space>' +
        '<TOKEN>definition</TOKEN><Space> </Space>' +
        '<TOKEN>*/</TOKEN>' +
      '</Option>' +
    '</LexicalProduction>' +
  '</LexicalDefinition>' +
  '<EOF/></Grammar>';


// ─── parseCharCode ────────────────────────────────────────────────────────────

describe('GrammarParser.parseCharCode', () => {
  const p = new GrammarParser('');

  it('converts #x0009 to tab', () => {
    assert.equal(p.parseCharCode('#x0009'), '\t');
  });
  it('converts #x000A to newline', () => {
    assert.equal(p.parseCharCode('#x000A'), '\n');
  });
  it('converts #x000D to carriage return', () => {
    assert.equal(p.parseCharCode('#x000D'), '\r');
  });
  it('converts #x0020 to space', () => {
    assert.equal(p.parseCharCode('#x0020'), ' ');
  });
  it('converts #x0041 to "A"', () => {
    assert.equal(p.parseCharCode('#x0041'), 'A');
  });
  it('is case-insensitive for hex digits', () => {
    assert.equal(p.parseCharCode('#x000a'), '\n');
  });
  it('returns non-hex strings unchanged', () => {
    assert.equal(p.parseCharCode('abc'), 'abc');
  });
  it('does not crash on non-string input (regression: array passed by xml2js)', () => {
    // xml2js returns an array when multiple <CharCode> siblings exist.
    // String() must be applied before .match() is called.
    assert.doesNotThrow(() => p.parseCharCode(['#x0009', '#x000A']));
  });
});


// ─── unescapeString ───────────────────────────────────────────────────────────

describe('GrammarParser.unescapeString', () => {
  const p = new GrammarParser('');

  it("strips surrounding single quotes: '+' → +", () => {
    assert.equal(p.unescapeString("'+'"), '+');
  });
  it('strips surrounding double quotes: "hello" → hello', () => {
    assert.equal(p.unescapeString('"hello"'), 'hello');
  });
  it('returns bare string unchanged', () => {
    assert.equal(p.unescapeString('hello'), 'hello');
  });
  it('handles single-char symbol: "*" → *', () => {
    assert.equal(p.unescapeString("'*'"), '*');
  });
});


// ─── Minimal grammar ─────────────────────────────────────────────────────────

describe('GrammarParser – minimal grammar (Start ::= Word, Word ::= [a-z]+)', () => {
  it('parses without error', async () => {
    await assert.doesNotReject(() => new GrammarParser(MINIMAL_XML).parse());
  });
  it('finds exactly 1 syntax rule', async () => {
    const g = await new GrammarParser(MINIMAL_XML).parse();
    assert.equal(g.rules.size, 1);
  });
  it('finds exactly 1 lexical token', async () => {
    const g = await new GrammarParser(MINIMAL_XML).parse();
    assert.equal(g.tokens.size, 1);
  });
  it('start symbol is "Start" (first rule)', async () => {
    const g = await new GrammarParser(MINIMAL_XML).parse();
    assert.equal(g.startSymbol, 'Start');
  });
  it('Start rule references "Word" as a nonterminal', async () => {
    const g = await new GrammarParser(MINIMAL_XML).parse();
    const rule = g.rules.get('Start');
    assert.ok(rule, 'Start rule must exist');
    assert.equal(rule.sequences[0][0].type, 'nonterminal');
    assert.equal(rule.sequences[0][0].value, 'Word');
  });
  it('Word token exists and has at least one pattern', async () => {
    const g = await new GrammarParser(MINIMAL_XML).parse();
    const token = g.tokens.get('Word');
    assert.ok(token, 'Word token must exist');
    assert.ok(token.patterns.length > 0);
  });
  it('Word token is not marked as skip', async () => {
    const g = await new GrammarParser(MINIMAL_XML).parse();
    assert.equal(g.tokens.get('Word').isSkip, false);
  });
});


// ─── Arithmetic grammar ───────────────────────────────────────────────────────

describe('GrammarParser – arithmetic grammar', () => {
  it('parses without error', async () => {
    await assert.doesNotReject(() => new GrammarParser(ARITHMETIC_XML).parse());
  });
  it('finds 3 syntax rules', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    assert.equal(g.rules.size, 3);
  });
  it('finds 2 lexical tokens', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    assert.equal(g.tokens.size, 2);
  });
  it('start symbol is "Expression"', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    assert.equal(g.startSymbol, 'Expression');
  });
  it('has rules: Expression, Term, Factor', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    assert.ok(g.rules.has('Expression'));
    assert.ok(g.rules.has('Term'));
    assert.ok(g.rules.has('Factor'));
  });
  it('Factor has 2 alternative sequences', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    assert.equal(g.rules.get('Factor').sequences.length, 2);
  });
  it('Expression contains a group with zeroOrMore quantifier', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    const items = g.rules.get('Expression').sequences[0];
    const group = items.find(i => i.type === 'group');
    assert.ok(group, 'Expression must have a group item');
    assert.equal(group.quantifier, 'zeroOrMore');
  });
  it('group inside Expression contains the "+" terminal', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    const items = g.rules.get('Expression').sequences[0];
    const group = items.find(i => i.type === 'group');
    const plusItem = group.sequences[0].find(i => i.type === 'terminal' && i.value === '+');
    assert.ok(plusItem, 'Group must contain "+" terminal');
  });
  it('Whitespace token has isSkip=true', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    assert.equal(g.tokens.get('Whitespace').isSkip, true);
  });
  it('Number token has isSkip=false', async () => {
    const g = await new GrammarParser(ARITHMETIC_XML).parse();
    assert.equal(g.tokens.get('Number').isSkip, false);
  });
});


// ─── Regressions ─────────────────────────────────────────────────────────────

describe('GrammarParser – Regression: multiple <CharCode> siblings in one <CharClass>', () => {
  it('does not throw "code.match is not a function"', async () => {
    await assert.doesNotReject(() => new GrammarParser(CHARCODE_XML).parse());
  });
  it('Ws token exists', async () => {
    const g = await new GrammarParser(CHARCODE_XML).parse();
    assert.ok(g.tokens.has('Ws'));
  });
  it('Ws token has isSkip=true (ws:definition option parsed correctly)', async () => {
    const g = await new GrammarParser(CHARCODE_XML).parse();
    assert.equal(g.tokens.get('Ws').isSkip, true);
  });
  it('charclass value is a non-empty string (not a raw array)', async () => {
    const g = await new GrammarParser(CHARCODE_XML).parse();
    const ws = g.tokens.get('Ws');
    const charclassItem = ws.patterns[0].find(i => i.type === 'charclass');
    assert.ok(charclassItem, 'Must have a charclass item');
    assert.equal(typeof charclassItem.value, 'string');
    assert.ok(charclassItem.value.length > 0, 'Charclass content must not be empty');
  });
});
