maiascript               ::= expression*
                           | eof

operation                ::= variableAssignment
variableAssignment       ::= conditionalExpression (('=' | '*=' | '/=' | '%=' | '+=' | '-=' | '<<=' | '>>=' | '&=' | '^=' | '|=' | '?=' | ':=') conditionalExpression)*

conditionalExpression    ::= logicalORExpression ('?' expression ':' expression)?

logicalXORExpression     ::= logicalORExpression ('^^' logicalORExpression)*
logicalORExpression      ::= logicalANDExpression ('||' logicalANDExpression)*
logicalANDExpression     ::= bitwiseXORExpression ('&&' bitwiseXORExpression)*
bitwiseXORExpression     ::= bitwiseORExpression ('^' bitwiseORExpression)*
bitwiseORExpression      ::= bitwiseANDExpression ('|' bitwiseANDExpression)*
bitwiseANDExpression     ::= equalityExpression ('&' equalityExpression)*

equalityExpression       ::= relationalExpression (('==' | '!=') relationalExpression)*
relationalExpression     ::= shiftExpression (('<' | '>' | '<=' | '>=') shiftExpression)*
shiftExpression          ::= additiveExpression (('<<' | '>>') additiveExpression)*
additiveExpression       ::= powerExpression (('+' | '-') powerExpression)*
powerExpression          ::= multiplicativeExpression ('**' multiplicativeExpression)*
multiplicativeExpression ::= unaryExpression (('*' | '/' | '%') unaryExpression)*

unaryExpression          ::= '++' primary
                           | '--' primary
                           | primary '++'
                           | primary '--'
                           | '+' primary
                           | '-' primary
                           | '~' primary
                           | '!' primary
                           | primary
                           
primary                  ::= member
                           | value
                           | parenthesizedExpression
                           | type identifier

statement                ::= namespace
                           | function
                           | include
                           | local
                           | if
                           | do
                           | while
                           | for
                           | foreach
                           | try
                           | test
                           | switch
                           | break
                           | continue
                           | return
                           | throw
                           | export
                           | import
                           | global
                           | typeof
                           | empty
                           
namespace                ::= 'namespace' identifier ('.' identifier)* block
function                 ::= ('async' | 'function' | 'plain')? identifier ('.' identifier)* '(' arguments? ')' ( block | '=' expression )
include                  ::= 'include' '(' expression ')'
global                   ::= 'global' expression
local                    ::= 'local' expression
if                       ::= 'if' '(' expression ')' statement elseif* else?
elseif                   ::= 'elseif' '(' expression ')' statement
else                     ::= 'else' statement
do                       ::= 'do' statement 'while' '(' expression ')'
while                    ::= 'while' '(' expression ')' statement
for                      ::= 'for' '(' (expression? | variableDeclaration) ';' expression? ';' expression? ')' statement
foreach                  ::= 'foreach' '(' expression ';' identifier ';' identifier ')' statement
try                      ::= 'try' block catch?
test                     ::= 'test' '(' expression? (';' expression? (';' expression?)?)? ')' block catch?
catch                    ::= 'catch' '(' expression ')' block
switch                   ::= 'switch' '(' expression ')' '{' case* default? '}'
case                     ::= 'case' expression ':' (statement | expression)*
default                  ::= 'default' ':' (statement | expression)*
break                    ::= 'break'
continue                 ::= 'continue'
return                   ::= 'return' expression?
throw                    ::= 'throw' expression
export                   ::= 'export' expression
import                   ::= 'import' expression
typeof                   ::= 'typeof' expression
empty                    ::= ';'

block                    ::= '{' (statement | expression | comment)* '}'

variableDeclaration      ::= type? identifier ('=' expression)?

type                     ::= 'i32' | 'i64' | 'f32' | 'f64'

arguments                ::= expression (',' expression)*

member                   ::= identifier ('.' identifier)* '(' arguments* ')'
                           | identifier ('.' identifier)* ('[' expression ']')*

array                    ::= '{' element (',' element)* '}'
matrix                   ::= '[' row? (';' row)* ']'

element                  ::= (key ':')? expression
key                      ::= string

row                      ::= column (',' column)*
column                   ::= expression

parenthesizedExpression  ::= '(' expression ')'

value                    ::= real
                           | complex
                           | string
                           | array
                           | matrix
                           | null
                           | true
                           | false
                           
expression               ::= statement
                           | operation
                           | comment

whitespace               ::= whitespace^token
                          /* ws: definition */

/* ===============================
          LEXICAL RULES
   =============================== */

<?TOKENS?>

eof                      ::= $

identifier               ::= (firstIdentifierChar identifierChar*) - reservedWord
                           
reservedWord             ::= keyword
                           | nullLiteral
                           | booleanLiteral

keyword                  ::= 'namespace'
                           | 'async'
                           | 'function'
                           | 'plain'
                           | 'include'
                           | 'global'
                           | 'local'
                           | 'if'
                           | 'elseif'
                           | 'else'
                           | 'do'
                           | 'while'
                           | 'for'
                           | 'foreach'
                           | 'try'
                           | 'catch'
                           | 'test'
                           | 'switch'
                           | 'case'
                           | 'default'
                           | 'break'
                           | 'continue'
                           | 'return'
                           | 'throw'
                           | 'export'
                           | 'import'
                           | 'typeof'
                           | 'i32'
                           | 'i64'
                           | 'f32'
                           | 'f64'
                           
nullLiteral              ::= null
booleanLiteral           ::= true
                           | false

null                     ::= 'null'
true                     ::= 'true'
false                    ::= 'false'

firstIdentifierChar      ::= '$' | '_' | [A-Za-z]
identifierChar           ::= '$' | '_' | [0-9] | [A-Za-z]

/* Numbers */

/* Complex Numbers */
complex                  ::= real? imaginary
real                     ::= '-'? digit+ ('.' digit+)? (('e' | 'E') ('+' | '-')? digit+)?
imaginary                ::= (('+' | '-')? real '*' 'i')
digit                    ::= [0-9]

/* Strings */
string                   ::= '"' (unicode | '\"' | '\\' | '\/' | '\b' | '\f' | '\n' | '\r' | '\t')* '"'

unicode                  ::= alphabet - ["#x005C]
alphabet                 ::= #x0009
                           | #x000A
                           | #x000D
                           | [#x0020-#xD7FF]
                           | [#xE000-#xFFFD]
                           | [#x10000-#x10FFFF]

/* Comments */
comment                  ::= singleLineComment

singleLineComment        ::= '//' (sourceCharacter - lineTerminator)*
                           | '#'  (sourceCharacter - lineTerminator)*

sourceCharacter          ::= .

lineTerminator           ::= #x000A
                           | #x000D
                           | #x2028
                           | #x2029

/* Whitespace */
whitespace               ::= [#x0009#x000A#x000D#x0020]+