a = ;
b = ;
d = core.add(a, b);
system.println();
d = core.sub(a, b);
system.println();
d = core.mul(a, b);
system.println();
d = core.div(a, b);
system.println();
d = core.mod(a, b);
system.println();
d = core.power(a, b);
system.println();
undefined(d = a, b);
system.println();
undefined(d = a, b);
system.println();
d = core.bitwiseAND(a, b);
system.println();
d = core.bitwiseOR(a, b);
system.println();
d = core.bitwiseXOR(a, b);
system.println();
d = core.logicalAND(a, b);
system.println();
d = core.logicalOR(a, b);
system.println();
d = a;
undefined(system.println());
d = b;
undefined(system.println());
d = a;
system.println();
d = b;
system.println();