a=1;
b=2.0;
c="Hello World!";
d=[1,2.0];
e=[];
f=[[1,2],[3,4]];
g=[[5,6],[7,8]];
h={a: 1,b: 2.0,"c": "Hello World!"};
i={};
system.println(a);
system.println(b);
system.println(c);
system.println(d);
system.println(e);
system.println(f);
system.println(g);
system.println(JSON.stringify(h));
system.println(JSON.stringify(i));
